config_route: trazas_app_config
menu:
    trazas:
        title: Trazas
        type: toggle
        icon: 'mdi mdi-view-quilt'
        includes: trazas
        children:
            home:
                title: 'Activar trazas'
                type: link
                state: trazas.activarT
            hisaccion:
                title: 'Trazas de acción'
                type: link
                state: trazas.hisaccion
            hisdato:
                title: 'Trazas de datos'
                type: link
                state: trazas.hisdato
            hisexcepcion:
                title: 'Trazas de excepción'
                type: link
                state: trazas.hisexcepcion
